name: myunicircle1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2  
  animated_text_kit: ^4.2.3
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/UNICIRCLELOGO2.png
    - assets/AppMainPic1.jpg
    - assets/AppMainPic2.jpg
    - assets/AppMainPic3.jpg
    - assets/food_data.json
